version: '3.4'

services:
  database:
    image: postgres:12
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
