// <auto-generated />
namespace phoneBookAPI.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion
open Npgsql.EntityFrameworkCore.PostgreSQL.Metadata
open PhoneBook.Data

[<DbContext(typeof<Context.DatabaseContext>)>]
type DatabaseContextModelSnapshot() =
    inherit ModelSnapshot()

    override this.BuildModel(modelBuilder: ModelBuilder) =
        modelBuilder

            .UseIdentityByDefaultColumns().HasAnnotation("Relational:MaxIdentifierLength", 63)
            .HasAnnotation("ProductVersion", "5.0.0")
            |> ignore

        modelBuilder.Entity("PhoneBook.Model.Contact", (fun b ->

            b.Property<int>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .UseIdentityByDefaultColumn() |> ignore
            b.Property<string>("Name")
                .IsRequired(true)
                .HasColumnType("text") |> ignore

            b.HasKey("Id") |> ignore

            b.ToTable("Contacts") |> ignore

        )) |> ignore

        modelBuilder.Entity("PhoneBook.Model.PhoneNumber", (fun b ->

            b.Property<int>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .UseIdentityByDefaultColumn() |> ignore
            b.Property<Nullable<int>>("ContactId")
                .IsRequired(true)
                .HasColumnType("integer") |> ignore
            b.Property<string>("Number")
                .IsRequired(false)
                .HasColumnType("text") |> ignore
            b.Property<string>("Type")
                .IsRequired(false)
                .HasColumnType("text") |> ignore

            b.HasKey("Id") |> ignore


            b.HasIndex("ContactId") |> ignore

            b.ToTable("PhoneNumbers") |> ignore

        )) |> ignore

        modelBuilder.Entity("PhoneBook.Model.PhoneNumber", (fun b ->
            b.HasOne("PhoneBook.Model.Contact",null)
                .WithMany("PhoneNumbers")
                .HasForeignKey("ContactId") |> ignore
        )) |> ignore

